language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.8.1"
  - DJANGO="django==1.7.8"
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.5.12"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install flake8

before_script:
  - flake8 --exclude=south_migrations --ignore=E501,E225,E128,E126,E402,F401,F403 contact_form
  - cd contact_form/tests

script: python ./runtests.py
